/*
 * PawCare Pet Clinic & Grooming — business data for the chatbot.
 * Everything the bot "knows" lives here: contact details, hours, services,
 * prices and the Q&A library. Edit this file to adapt the bot to another business.
 *
 * Text placeholders you can use in any answer:
 *   {name} {short} {city} {address} {phone} {emergency} {email} {hours}
 *   {price:<serviceId>}  → price range of a service, e.g. {price:bath} → ₹500–₹900
 */
(function (root) {
  var CONFIG = {
    business: {
      name: 'PawCare Pet Clinic & Grooming',
      shortName: 'PawCare',
      city: 'Bengaluru',
      street: '42 Maple Lane, Green Park Road',
      phone: '+91 98765 43210',
      emergencyPhone: '+91 98765 00911',
      email: 'hello@pawcareclinic.in',
      currency: '₹',
      openDays: [1, 2, 3, 4, 5, 6],          // 0 = Sunday … 6 = Saturday
      openTime: '09:00',
      closeTime: '19:00',
      lastSlot: '18:00',                      // last appointment start time
      slotMinutes: 30,
      minLeadMinutes: 60,                     // same-day bookings need this much notice
      bookingWindowDays: 90,
      hoursText: 'Monday to Saturday, 9 AM to 7 PM (closed on Sundays)',
      parking: 'Free parking is right in front of the clinic, with room for a few cars and plenty of two-wheelers, plus paid street parking nearby if it gets busy.',
      payment: ['cash', 'all major credit and debit cards', 'UPI and online payments (GPay, PhonePe, Paytm)'],
      cancellation: 'Free cancellation or rescheduling up to 4 hours before the appointment; later changes or no-shows may have a ₹200 fee.',
      cancellationHours: 4,
      homePickup: { available: true, radiusKm: 8, feeEachWay: 250, freeWith: 'spa' },
      multiPetDiscount: 10                    // % off every extra pet in the same visit
    },

    /* Pets we serve. "group" drives pet-specific answers and pricing size. */
    pets: [
      { id: 'dog', label: 'dog', plural: 'dogs', emoji: '🐶', group: 'dog', words: ['dog', 'dogs', 'puppy', 'puppies', 'pup', 'pups', 'doggy', 'doggo', 'pooch'] },
      { id: 'cat', label: 'cat', plural: 'cats', emoji: '🐱', group: 'cat', words: ['cat', 'cats', 'kitten', 'kittens', 'kitty', 'kitties'] },
      { id: 'bird', label: 'bird', plural: 'birds', emoji: '🐦', group: 'bird', words: ['bird', 'birds', 'parrot', 'parrots', 'budgie', 'budgies', 'cockatiel', 'cockatiels', 'lovebird', 'lovebirds', 'macaw', 'macaws', 'conure', 'conures', 'canary', 'canaries', 'finch', 'finches', 'cockatoo', 'cockatoos'] },
      { id: 'rabbit', label: 'rabbit', plural: 'rabbits', emoji: '🐰', group: 'rabbit', words: ['rabbit', 'rabbits', 'bunny', 'bunnies'] },
      { id: 'hamster', label: 'hamster', plural: 'hamsters', emoji: '🐹', group: 'small', words: ['hamster', 'hamsters'] },
      { id: 'guinea pig', label: 'guinea pig', plural: 'guinea pigs', emoji: '🐹', group: 'small', words: ['guinea pig', 'guinea pigs', 'guineapig', 'cavy'] },
      { id: 'sheep', label: 'sheep', plural: 'sheep', emoji: '🐑', group: 'farm', words: ['sheep', 'lamb', 'lambs', 'ewe', 'ram'] },
      { id: 'goat', label: 'goat', plural: 'goats', emoji: '🐐', group: 'farm', words: ['goat', 'goats'] },
      { id: 'cow', label: 'cow', plural: 'cows', emoji: '🐄', group: 'farm', words: ['cow', 'cows', 'calf', 'calves', 'cattle', 'buffalo', 'bull'] },
      { id: 'horse', label: 'horse', plural: 'horses', emoji: '🐴', group: 'farm', words: ['horse', 'horses', 'pony', 'ponies', 'foal', 'mare', 'stallion'] },
      { id: 'other', label: 'pet', plural: 'pets', emoji: '🐾', group: 'small', words: ['ferret', 'ferrets', 'turtle', 'turtles', 'tortoise', 'tortoises', 'chinchilla', 'chinchillas', 'hedgehog', 'hedgehogs', 'gerbil', 'gerbils', 'mouse', 'mice', 'rat', 'rats', 'iguana', 'lizard', 'snake'] }
    ],

    /* Breeds → pet type and size (s / m / l) used for price estimates. */
    breeds: {
      dog: {
        s: ['chihuahua', 'pomeranian', 'pom', 'shih tzu', 'shihtzu', 'shih-tzu', 'yorkie', 'yorkshire terrier', 'maltese', 'pug', 'dachshund', 'toy poodle', 'lhasa apso', 'lhasa', 'papillon', 'miniature pinscher', 'min pin', 'jack russell', 'cavalier', 'king charles', 'french bulldog', 'frenchie', 'bichon', 'bichon frise', 'havanese', 'westie', 'west highland terrier', 'miniature schnauzer', 'indian spitz', 'spitz', 'pekingese', 'boston terrier', 'cockapoo', 'maltipoo', 'shih poo'],
        m: ['beagle', 'cocker spaniel', 'cocker', 'border collie', 'bulldog', 'english bulldog', 'corgi', 'australian shepherd', 'aussie', 'shiba inu', 'shiba', 'basset hound', 'basset', 'indie', 'indian pariah', 'pariah', 'desi', 'schnauzer', 'bull terrier', 'staffy', 'staffordshire terrier', 'whippet', 'springer spaniel', 'chow chow', 'chow', 'kombai', 'chippiparai', 'labradoodle', 'goldendoodle', 'pit bull', 'pitbull', 'american bully'],
        l: ['labrador', 'labrador retriever', 'lab', 'golden retriever', 'golden', 'retriever', 'german shepherd', 'gsd', 'alsatian', 'rottweiler', 'rottie', 'doberman', 'dobermann', 'boxer', 'great dane', 'saint bernard', 'st bernard', 'newfoundland', 'bernese', 'bernese mountain dog', 'mastiff', 'bullmastiff', 'husky', 'siberian husky', 'malamute', 'alaskan malamute', 'akita', 'great pyrenees', 'rhodesian ridgeback', 'weimaraner', 'belgian malinois', 'malinois', 'cane corso', 'dogo argentino', 'rajapalayam', 'mudhol hound', 'mudhol', 'standard poodle', 'poodle', 'samoyed', 'dalmatian', 'irish setter', 'old english sheepdog', 'leonberger', 'tibetan mastiff']
      },
      cat: {
        s: ['persian', 'siamese', 'bengal', 'ragdoll', 'british shorthair', 'sphynx', 'himalayan', 'scottish fold', 'abyssinian', 'russian blue', 'exotic shorthair', 'domestic shorthair', 'domestic longhair', 'burmese', 'birman', 'tabby', 'calico', 'indie cat', 'indian cat', 'american shorthair', 'turkish angora', 'devon rex'],
        m: ['maine coon', 'norwegian forest', 'savannah']
      },
      bird: { s: ['parrot', 'budgie', 'budgerigar', 'cockatiel', 'lovebird', 'macaw', 'african grey', 'cockatoo', 'conure', 'finch', 'canary', 'pigeon', 'myna', 'parakeet', 'ringneck', 'indian ringneck', 'sun conure', 'eclectus'] },
      rabbit: { s: ['lionhead', 'holland lop', 'mini lop', 'netherland dwarf', 'angora', 'rex', 'dutch', 'flemish giant', 'mini rex', 'english lop', 'new zealand white'] },
      hamster: { s: ['syrian', 'dwarf', 'roborovski', 'campbell', 'winter white', 'teddy bear hamster'] },
      'guinea pig': { s: ['peruvian', 'teddy', 'american', 'skinny pig', 'texel', 'silkie'] },
      sheep: { s: ['merino', 'deccani', 'suffolk', 'dorper', 'nellore', 'marwari sheep'] },
      goat: { s: ['boer', 'jamunapari', 'beetal', 'sirohi', 'barbari', 'saanen', 'osmanabadi', 'black bengal', 'nubian'] },
      cow: { s: ['gir', 'sahiwal', 'jersey', 'holstein', 'red sindhi', 'tharparkar', 'ongole', 'kankrej', 'hallikar', 'murrah'] },
      horse: { s: ['marwari', 'kathiawari', 'thoroughbred', 'arabian', 'shetland', 'mustang', 'quarter horse', 'friesian', 'appaloosa'] }
    },

    /*
     * Services. prices = [small, medium, large] or flat. "kw" = words that map a
     * customer's need to this service. "dur" = typical duration.
     */
    services: [
      { id: 'bath', name: 'Basic Bath', cat: 'groom', prices: [500, 700, 900], dur: 'about 45 minutes to 1 hour', desc: 'shampoo, conditioner, blow-dry and brush-out', kw: ['bath', 'bathe', 'bathing', 'wash', 'washing', 'shower', 'shampoo', 'smells', 'smelly', 'stinky', 'stinks', 'dirty', 'muddy'] },
      { id: 'groom', name: 'Full Grooming', cat: 'groom', prices: [1200, 1600, 2200], dur: 'about 1.5 to 2.5 hours, depending on size and coat', desc: 'bath, haircut, nail trim and ear cleaning', kw: ['full groom', 'full grooming', 'grooming', 'groom', 'complete groom', 'makeover', 'grooming session'] },
      { id: 'deshed', name: 'De-shedding', cat: 'groom', prices: [900, 1200, 1600], dur: 'about 1 to 1.5 hours', desc: 'deep undercoat brush-out and de-shedding bath', kw: ['deshed', 'deshedding', 'shedding', 'sheds', 'shed', 'undercoat', 'loose hair', 'losing fur', 'hair fall', 'moulting', 'molting'] },
      { id: 'haircut', name: 'Haircut/Styling', cat: 'groom', prices: [800, 1100, 1500], dur: 'about 1 to 1.5 hours', desc: 'breed cut or style of your choice', kw: ['haircut', 'hair cut', 'styling', 'style', 'trim his hair', 'trim her hair', 'trim', 'clip', 'clipping', 'shave', 'summer cut', 'puppy cut', 'teddy bear cut', 'lion cut', 'fur cut', 'cut his fur', 'cut her fur'] },
      { id: 'nail', name: 'Nail Trim', cat: 'groom', prices: [250, 300, 400], dur: 'about 15 minutes', desc: 'nail clipping and filing', kw: ['nail', 'nails', 'claw', 'claws', 'nail trim', 'nail cut', 'pedicure', 'paw trim'] },
      { id: 'ear', name: 'Ear Cleaning', cat: 'groom', prices: [250, 300, 350], dur: 'about 15 minutes', desc: 'gentle ear cleaning', kw: ['ear cleaning', 'clean ears', 'clean his ears', 'clean her ears', 'ears cleaned', 'ear clean', 'ears'] },
      { id: 'teeth', name: 'Teeth Cleaning', cat: 'groom', prices: [400, 500, 600], dur: 'about 20 to 30 minutes', desc: 'gentle non-anaesthetic brushing and polish', kw: ['teeth', 'tooth', 'dental', 'teeth cleaning', 'brush teeth', 'bad breath', 'tartar'] },
      { id: 'flea', name: 'Flea & Tick Treatment', cat: 'groom', prices: [600, 800, 1000], dur: 'about 45 minutes', desc: 'medicated bath and comb-out', kw: ['flea', 'fleas', 'tick', 'ticks', 'lice', 'flea treatment', 'tick treatment', 'parasites'] },
      { id: 'matted', name: 'Matted Fur Removal', cat: 'groom', prices: [700, 1000, 1400], dur: 'about 1 to 2 hours, depending on the matting', desc: 'careful de-matting or a gentle short clip', kw: ['matted', 'mats', 'matting', 'tangles', 'tangled', 'knots', 'knotted', 'clumps'] },
      { id: 'spa', name: 'Spa Package', cat: 'groom', prices: [1800, 2400, 3200], dur: 'about 2.5 to 3 hours', desc: 'bath, full groom, nails, ears, teeth and a paw balm', kw: ['spa', 'spa package', 'spa day', 'pamper', 'pampering', 'luxury'] },
      { id: 'vacc', name: 'Vaccination', cat: 'vet', prices: [500, 600, 700], perUnit: 'per vaccine', dur: 'about 20 minutes', desc: 'core and lifestyle vaccines with a quick health check', kw: ['vaccination', 'vaccinations', 'vaccine', 'vaccines', 'vaccinate', 'vaccinated', 'shots', 'shot', 'jab', 'jabs', 'booster', 'rabies'] },
      { id: 'checkup', name: 'General Checkup', cat: 'vet', prices: [600, 700, 800], dur: 'about 30 minutes', desc: 'nose-to-tail health check with our vet', kw: ['checkup', 'check up', 'check-up', 'health check', 'general checkup', 'examination', 'consultation', 'vet visit', 'see a vet', 'see the vet', 'see a doctor', 'vet check'] },
      { id: 'deworm', name: 'Deworming', cat: 'vet', prices: [250, 350, 450], dur: 'about 10 minutes', desc: 'deworming as advised by our vet', kw: ['deworm', 'deworming', 'dewormed', 'worms', 'worming'] },
      { id: 'microchip', name: 'Microchipping', cat: 'vet', flat: 1200, dur: 'about 10 minutes', desc: 'a tiny ID chip, registered to you', kw: ['microchip', 'microchipping', 'microchipped', 'chip', 'chipped', 'chipping'] },
      { id: 'firstvisit', name: 'Puppy/Kitten First Visit', cat: 'vet', flat: 900, dur: 'about 45 minutes', desc: 'full health check, vaccine and deworming plan and care tips', kw: ['puppy visit', 'kitten visit', 'puppy first visit', 'kitten first visit', 'new puppy', 'new kitten', 'just adopted', 'first vet visit for my puppy'] },
      { id: 'spay', name: 'Spay/Neuter Consultation', cat: 'vet', flat: 700, dur: 'about 30 minutes', desc: 'a consultation about spaying or neutering', kw: ['spay', 'spaying', 'spayed', 'neuter', 'neutering', 'neutered', 'castrate', 'castration', 'sterilize', 'sterilise', 'sterilization', 'sterilisation', 'desex'] },
      { id: 'senior', name: 'Senior Pet Checkup', cat: 'vet', prices: [1200, 1400, 1600], dur: 'about 45 minutes', desc: 'detailed check for older pets', kw: ['senior checkup', 'senior check', 'senior pet checkup', 'senior care', 'old age checkup'] },
      { id: 'farm', name: 'Farm Animal Visit', cat: 'farm', from: 2500, onRequest: true, dur: 'depends on the herd size and services', desc: 'our team visits your farm, arranged on request', kw: ['farm visit', 'farm animal visit', 'farm call', 'visit my farm', 'come to my farm', 'come to the farm'] }
    ],

    /* Quick-reply buttons for common questions (never for services). */
    quickReplies: ['📅 Book a visit', '💰 Prices', '🕘 Opening hours', '📍 Location', '🚗 Home pickup', '🚨 Emergency'],

    ui: {
      batchDelayMs: 4000,   // wait this long after the last message/keystroke before replying
      chipDelayMs: 1500,    // shorter wait after tapping a button
      autoOpen: false
    },

    /*
     * Q&A library. Each entry:
     *   req: groups of keywords — at least one keyword from EVERY group must appear.
     *        "word*" matches any ending (groom* → grooming, groomer…).
     *   k:   optional bonus keywords.
     *   q:   true → only answered when the message is a question.
     *   a:   the answer, or { dog, cat, bird, rabbit, small, farm, default } for pet-specific answers.
     */
    qa: [
      { id: 'groom_freq', q: true,
        req: [['how often', 'how frequently', 'frequency', 'how many times', 'how regularly', 'how frequent', 'how long between', 'every how many'], ['groom*', 'haircut*', 'trim*', 'brush*', 'groomer']],
        a: {
          dog: 'Most dogs do well with a full groom every 4–8 weeks: long or curly coats closer to every 4–6 weeks, short coats every 8–12 weeks. Brushing a few times a week at home keeps things tidy in between.',
          cat: 'Cats do a lot of their own grooming, so a professional groom every 6–12 weeks is usually plenty, a little more often for long-haired breeds like Persians. Gentle brushing once or twice a week at home helps prevent mats.',
          bird: 'Most birds need a nail, beak or wing trim every 1–3 months, depending on their species and how active they are. Our team will suggest a routine once they meet your bird.',
          rabbit: 'Rabbits need brushing a few times a week (daily while moulting) and a nail trim every 4–6 weeks. Long-haired breeds like Angoras benefit from a professional groom every 6–8 weeks.',
          small: 'Hamsters, guinea pigs and other small pets mostly need a nail trim every 4–8 weeks plus gentle brushing, and long-haired guinea pigs need a bit more coat care. We keep their sessions short and calm.',
          farm: 'For sheep, goats, cows and horses it depends on the season and the animal\'s work, from regular brushing and hoof checks to yearly shearing for sheep. Our Farm Animal Visit team will set up a routine with you.',
          default: 'Most dogs need a groom every 4–8 weeks and cats every 6–12 weeks, while smaller pets mostly need a nail trim every month or two. Tell me which pet you have and I can be more specific!'
        } },
      { id: 'bath_freq', q: true,
        req: [['how often', 'how frequently', 'frequency', 'how many times', 'how regularly', 'how frequent', 'every how many'], ['bath*', 'wash*', 'shampoo*']],
        a: {
          dog: 'Most dogs need a bath every 3–6 weeks; very active outdoor dogs may need one more often, but bathing too frequently can dry out their skin. Short-coated breeds can usually go a little longer between baths.',
          cat: 'Most cats rarely need a bath because they keep themselves clean; every few months, or when they get into something messy, is plenty. Long-haired and senior cats sometimes need a little extra help.',
          rabbit: 'Rabbits shouldn\'t be given full water baths, as it can stress them badly; spot-cleaning and brushing are the way to go. Our groomers are happy to show you how.',
          bird: 'Most birds love a light misting or a shallow water dish a few times a week rather than a full bath. Our team can share tips for your bird\'s species.',
          small: 'Hamsters and guinea pigs generally shouldn\'t be bathed in water; hamsters use sand baths and guinea pigs usually only need spot-cleaning. We can help with gentle grooming instead.',
          farm: 'Farm animals usually only need a wash before shows or when they\'re very dirty, plus regular brushing. Our Farm Animal Visit team can advise on a routine.',
          default: 'Dogs usually need a bath every 3–6 weeks, while cats and small pets rarely need one at all. Tell me your pet type and I can give you a better idea!'
        } },
      { id: 'first_groom', q: true,
        req: [['puppy', 'puppies', 'kitten*', 'young', 'baby', 'babies'], ['first*', 'start*', 'what age', 'how old', 'how young', 'old enough', 'when can', 'when should']],
        k: ['groom*', 'bath*', 'haircut'],
        a: 'Puppies and kittens can have their first gentle groom from about 10–12 weeks, once our vet confirms they\'re ready and they\'ve had their first vaccines. We keep that first session short and fun, with lots of treats, so they learn that grooming is a happy thing!' },
      { id: 'vacc_before_groom', q: true,
        req: [['vaccin*', 'shot', 'shots', 'jab*', 'rabies'], ['groom*', 'bath*', 'haircut*', 'spa', 'before']],
        a: 'Yes, we ask that pets are up to date on their core vaccines (like rabies and distemper for dogs, or the core cat vaccines) before grooming, to keep everyone safe. If your pet is due, we can do the vaccination at the same visit.' },
      { id: 'matted',
        req: [['mat', 'mats', 'matted', 'matting', 'tangle*', 'knot*', 'clump*', 'dreadlock*']],
        a: 'Matted fur pulls on the skin and can be quite uncomfortable, so it\'s best removed by a professional rather than cut at home. Our Matted Fur Removal ({price:matted}) is done gently, and sometimes a short clip is the kindest option.' },
      { id: 'shedding',
        req: [['shed', 'sheds', 'shedding', 'moult*', 'molt*', 'hair fall', 'hair everywhere', 'fur everywhere', 'losing hair', 'losing fur', 'loose hair', 'undercoat']],
        a: 'Some shedding is completely natural, especially for double-coated breeds and during seasonal changes. Regular brushing plus our De-shedding treatment ({price:deshed}) removes a lot of the loose undercoat, and if you\'re worried about how much hair is falling out, our vet can take a look.' },
      { id: 'anxious',
        req: [['anxious', 'anxiety', 'nervous', 'scared', 'afraid', 'fearful', 'frightened', 'stressed', 'stress', 'panics', 'panic', 'timid', 'shy', 'hates grooming', 'hates baths', 'hates the groomer', 'hates the vet', 'gets scared']],
        a: 'Anxious pets are in good hands with us: we go slowly, use calm handling, take breaks and keep the noise down. Just mention it when booking and we\'ll set aside extra time; a short "happy visit" first can help too.' },
      { id: 'aggressive',
        req: [['bite', 'bites', 'biting', 'bit someone', 'aggressive', 'aggression', 'snaps', 'snapping', 'growls', 'growling', 'attacks', 'reactive', 'not friendly', 'unfriendly']],
        a: 'Thanks for letting us know, that really helps us plan. Our team is experienced with nervous and reactive pets: we use gentle handling, take breaks, and may use a soft muzzle for safety, and we\'ll note it on the booking so there\'s extra time.' },
      { id: 'senior',
        req: [['senior', 'elderly', 'geriatric', 'old dog', 'old cat', 'older dog', 'older cat', 'old pet', 'older pet', 'aging', 'ageing', 'very old', 'getting old']],
        a: 'Senior pets get extra-gentle care here: shorter sessions, non-slip mats, rest breaks and warm (never hot) drying. We also offer a Senior Pet Checkup ({price:senior}) if you\'d like our vet to keep an eye on things.' },
      { id: 'long_short_hair',
        req: [['long hair*', 'long-hair*', 'longhair*', 'short hair*', 'short-hair*', 'shorthair*', 'double coat*', 'double-coat*', 'coat type', 'fluffy', 'curly coat']],
        a: 'Long-haired breeds like Shih Tzus, Persians and Golden Retrievers need brushing several times a week and a groom every 4–6 weeks to prevent mats. Short-haired breeds like Beagles, Labs and most cats need less trimming but still benefit from regular baths, brushing and de-shedding.' },
      { id: 'flea_tick', q: true,
        req: [['flea*', 'tick', 'ticks', 'lice', 'parasite*']],
        a: 'Fleas and ticks are common, especially in warm and rainy months, so check the ears, neck, armpits and between the toes regularly. Our Flea & Tick Treatment ({price:flea}) gives a thorough clean, and our vet can advise on the right prevention for your pet.' },
      { id: 'nails', q: true,
        req: [['nail*', 'claw*']],
        a: 'Most pets need a nail trim every 3–6 weeks; if you can hear clicking on the floor, it\'s usually time. Our Nail Trim ({price:nail}) is quick and gentle, and we file any sharp edges too.' },
      { id: 'ears', q: true,
        req: [['ear', 'ears']],
        a: 'It\'s good to check ears weekly and clean them every 2–4 weeks, more often for floppy-eared breeds like Spaniels and Beagles. Our Ear Cleaning ({price:ear}) is gentle, and if you notice redness, a smell or discharge, our vet should take a look.' },
      { id: 'dental', q: true,
        req: [['teeth', 'tooth', 'dental', 'breath', 'tartar', 'gums']],
        a: 'Brushing your pet\'s teeth a few times a week with a pet-safe toothpaste is the best habit you can build. Our Teeth Cleaning ({price:teeth}) is a gentle, non-anaesthetic clean and polish, and anything deeper is assessed by our vet.' },
      { id: 'what_to_bring', q: true,
        req: [['what should i bring', 'what to bring', 'what do i bring', 'what do i need to bring', 'should i bring anything', 'bring anything', 'anything to bring', 'what should i carry', 'what to carry', 'how to prepare', 'how should i prepare', 'what do i need for']],
        a: 'Just bring your pet on a leash or in a secure carrier, their vaccination records, and any notes on health issues or past grooming. A favourite toy or treat can help them feel at home too!' },
      { id: 'duration', q: true,
        req: [['how long', 'how much time', 'duration', 'take long', 'takes long', 'how many hours', 'how many minutes']],
        a: 'A Basic Bath takes about 45 minutes to an hour, Full Grooming about 1.5 to 2.5 hours depending on size and coat, and a Nail Trim about 15 minutes. Tell me the service and I can give you a closer estimate!' },
      { id: 'packages',
        req: [['package*', 'combo*', 'bundle*', 'deal', 'deals', 'offer', 'offers', 'discount*', 'promo*', 'coupon*', 'membership']],
        a: 'Our Spa Package ({price:spa}) bundles a bath, full groom, nail trim, ear cleaning, teeth cleaning and a paw balm for less than booking them separately. We also give 10% off every extra pet you bring in the same visit.' },
      { id: 'home_pickup',
        req: [['pickup', 'pick up', 'pick-up', 'pick him up', 'pick her up', 'pick them up', 'drop off', 'drop-off', 'collect my', 'transport', 'come to my home', 'come to my house', 'doorstep', 'home service', 'home visit', 'pet taxi']],
        a: 'Yes! We offer home pickup and drop within about 8 km of the clinic for ₹250 each way, and it\'s free with the Spa Package. Just mention it when booking and the team will confirm the timing.' },
      { id: 'farm',
        req: [['farm', 'farms', 'sheep', 'goat*', 'cow', 'cows', 'cattle', 'horse*', 'pony', 'ponies', 'livestock', 'buffalo*', 'donkey*']],
        a: 'Yes, we care for sheep, goats, cows and horses through our Farm Animal Visit, arranged on request from ₹2,500 plus travel. Our team comes to you for grooming, hoof checks, vaccinations and general health checks.' },
      { id: 'how_much_multi', q: true,
        req: [['how much', 'price', 'prices', 'cost', 'costs', 'charge', 'charges', 'rate', 'rates'], ['2', 'two', '3', 'three', '4', 'four', 'multiple', 'both', 'couple', 'several'], ['dogs', 'cats', 'pets', 'puppies', 'kittens', 'animals', 'rabbits', 'birds']],
        a: 'Each pet is priced by size, so for two dogs it\'s simply two of the chosen service (for example, two Full Grooms at ₹1,200–₹2,200 each), with 10% off the second dog in the same visit. Tell me their breeds and I\'ll work out a proper estimate!' },
      { id: 'multi_discount',
        req: [['discount*', 'cheaper', 'deal', 'offer', 'less', 'concession'], ['multiple', 'more than one', 'two', '2', 'three', '3', 'several', 'second', 'both', 'extra pet', 'another pet', 'all my']],
        a: 'Yes! When you bring more than one pet in the same visit, every extra pet gets 10% off. Just add them all to one booking.' },
      { id: 'cancellation', q: true,
        req: [['cancel*']],
        a: 'You can cancel or reschedule for free up to 4 hours before your appointment. After that, or for no-shows, a small ₹200 fee may apply.' },
      { id: 'reschedule', q: true,
        req: [['reschedul*', 'postpone', 'move my appointment', 'move my booking', 'change my appointment', 'change my booking', 'another day', 'different day']],
        a: 'Rescheduling is free up to 4 hours before your appointment; just message or call us at {phone}. If you\'re booking with me right now, simply tell me the new day or time.' },
      { id: 'late',
        req: [['late', 'delay*', 'running behind', 'stuck in traffic', 'few minutes late']],
        a: 'No worries, we hold your slot for 15 minutes. If you\'re running later than that, give us a call at {phone} and we\'ll fit you in or move you to the next free slot.' },
      { id: 'payment',
        req: [['pay', 'paying', 'payment*', 'upi', 'card', 'cards', 'cash', 'gpay', 'google pay', 'phonepe', 'paytm', 'credit card', 'debit card', 'net banking', 'online payment']],
        a: 'We accept cash, all major credit and debit cards, and UPI or online payments like GPay, PhonePe and Paytm. Payment is made at the clinic after the service.' },
      { id: 'parking',
        req: [['park', 'parking', 'car park']],
        a: 'Yes, free parking is right in front of the clinic, with room for a few cars and plenty of two-wheelers. There\'s also paid street parking nearby if it gets busy.' },
      { id: 'hours', q: true,
        req: [['open', 'opening', 'close', 'closing', 'closed', 'timing', 'timings', 'hours', 'what time do you', 'when are you', 'working hours', 'business hours', 'office hours']],
        a: 'We\'re open Monday to Saturday, 9 AM to 7 PM, and closed on Sundays. The last appointment slot starts at 6 PM.' },
      { id: 'sunday',
        req: [['sunday', 'sundays', 'weekend', 'weekends']], k: ['open', 'closed', 'work'],
        q: true,
        a: 'We\'re closed on Sundays so our team can rest, but we\'re open on Saturdays from 9 AM to 7 PM. For a Sunday emergency, please go to the nearest emergency vet or call {emergency}.' },
      { id: 'walk_in',
        req: [['walk in', 'walk-in', 'walk ins', 'walk-ins', 'walkin', 'walkins', 'without appointment', 'without an appointment', 'without booking', 'just come', 'just drop by', 'drop in', 'drop by', 'just show up', 'turn up']],
        a: 'Walk-ins are welcome whenever we have a free slot, but booking ahead guarantees your time, especially on Saturdays. I can book a slot for you right now if you like!' },
      { id: 'emergency_info',
        req: [['emergency', 'emergencies', 'urgent', '24/7', '24 hours', '24 7', 'after hours', 'night time', 'midnight']],
        a: 'If it\'s an emergency, please take your pet to the nearest emergency vet right away. You can also call our emergency line at {emergency}.' },
      { id: 'paperwork', q: true,
        req: [['paperwork', 'documents', 'document', 'forms', 'form', 'register', 'registration', 'first visit', 'new client', 'new patient', 'first time']],
        a: 'For a first visit there\'s just a short registration form with your details and your pet\'s health history, which takes about 5 minutes. Bring any vaccination records and previous vet notes if you have them.' },
      { id: 'vacc_records',
        req: [['record*', 'certificate*', 'card', 'proof', 'booklet', 'papers'], ['vaccin*', 'health', 'medical', 'shot', 'shots']],
        a: 'Yes, please bring your pet\'s vaccination card or certificate; a photo of it on your phone works too. If the records are missing, our vet can talk you through catching up.' },
      { id: 'vacc_schedule', q: true,
        req: [['vaccin*', 'shot', 'shots', 'jab*', 'booster*'], ['when', 'schedule', 'how often', 'which', 'what', 'age', 'due', 'need', 'needs', 'how many']],
        a: 'Our vet will guide you on the right vaccination schedule during your visit, since it depends on your pet\'s age, history and lifestyle. Vaccinations start from ₹500 per vaccine, and you can reach us at {phone} with any questions.' },
      { id: 'deworm', q: true,
        req: [['deworm*', 'worm', 'worms', 'worming']],
        a: 'Our vet will set the right deworming routine for your pet during the visit, since it depends on age and lifestyle. Deworming starts from {price:deworm}.' },
      { id: 'microchip',
        req: [['microchip*', 'chip', 'chipping', 'chipped']],
        a: 'Microchipping ({price:microchip}) is a quick, one-time procedure where a tiny chip is placed under the skin, so your pet can be identified and returned if they\'re ever lost. It only takes a few minutes and can be done at any visit.' },
      { id: 'spay_neuter',
        req: [['spay*', 'neuter*', 'castrat*', 'steriliz*', 'sterilis*', 'desex*']],
        a: 'Our Spay/Neuter Consultation ({price:spay}) is where our vet talks through whether it\'s right for your pet, the best timing and what to expect. Book a consultation and they\'ll walk you through everything.' },
      { id: 'stay_with_pet', q: true,
        req: [['stay', 'watch', 'be with', 'accompany', 'be there', 'be present', 'in the room', 'come inside', 'wait with']], k: ['pet', 'dog', 'cat', 'during', 'while', 'groom*'],
        a: 'For vet visits you\'re welcome to stay with your pet the whole time. For grooming, many pets actually settle better without their owner in the room, but you\'re welcome to wait in our lounge and we\'ll call you in if they need you.' },
      { id: 'sedation',
        req: [['sedat*', 'anaesthe*', 'anesthe*', 'tranquil*', 'knock him out', 'knock her out', 'drugged']],
        a: 'We never sedate pets for routine grooming. If a pet is extremely stressed, we stop and talk to you, and any sedation for a medical procedure is only ever decided by our vet after a proper examination.' },
      { id: 'location', q: true,
        req: [['where', 'address', 'location', 'located', 'directions', 'find you', 'map', 'how to reach', 'how do i get', 'which area', 'landmark']],
        a: 'We\'re at {address}. Free parking is right in front, and you can call {phone} if you need directions.' },
      { id: 'contact', q: true,
        req: [['phone number', 'your number', 'contact', 'call you', 'email', 'reach you', 'whatsapp', 'telephone', 'mobile number', 'get in touch', 'talk to someone', 'speak to someone', 'human']],
        a: 'You can call or WhatsApp us at {phone}, or email {email}. For emergencies, our line is {emergency}.' },
      { id: 'pets_served', q: true,
        req: [['groom*', 'treat', 'treats', 'accept', 'take', 'handle', 'serve', 'see', 'cater', 'work with', 'allowed', 'care for', 'look after', 'do you do'], ['cat', 'cats', 'dog', 'dogs', 'bird*', 'parrot*', 'rabbit*', 'bunny', 'bunnies', 'hamster*', 'guinea pig*', 'pets', 'animals', 'exotic*', 'puppies', 'kittens', 'small animals', 'which animals', 'what animals', 'kind of pets', 'types of pets']],
        a: 'We care for dogs, cats, birds, rabbits, hamsters and guinea pigs, and even sheep, goats, cows and horses through our Farm Animal Visit, plus other pets on request. Just tell me about yours!' },
      { id: 'other_pets',
        req: [['ferret*', 'turtle*', 'tortoise*', 'chinchilla*', 'hedgehog*', 'gerbil*', 'mouse', 'mice', 'rats', 'fish', 'snake*', 'lizard*', 'iguana*', 'exotic*', 'reptile*']],
        a: 'We see many small and exotic pets too, mostly for nail trims, gentle grooming and general checkups. Tell me what you have and our team will confirm what we can do.' },
      { id: 'staff_quals',
        req: [['qualified', 'qualification*', 'certified', 'experienced', 'experience', 'expert*', 'professional*', 'skilled', 'trained']], k: ['groomer*', 'vet', 'vets', 'staff', 'team', 'doctor*'],
        q: true,
        a: 'Our team is made up of qualified vets and certified, experienced groomers who are trained in gentle, low-stress handling. Every pet also gets a quick health check before grooming starts.' },
      { id: 'products',
        req: [['shampoo*', 'product*', 'conditioner*', 'chemical*', 'organic', 'natural', 'cologne', 'perfume', 'hypoallergenic']],
        q: true,
        a: 'We use gentle, pet-safe, soap-free shampoos and conditioners suited to each coat type, including hypoallergenic options for sensitive skin. You\'re also welcome to bring your pet\'s own shampoo.' },
      { id: 'home_bath', q: true,
        req: [['at home', 'myself', 'my own', 'diy', 'home groom*', 'by myself'], ['bath*', 'groom*', 'trim*', 'cut*', 'brush*', 'wash*']],
        a: 'You can definitely bathe and brush at home: use a pet-safe shampoo and lukewarm water, rinse well and dry thoroughly. Nail trims, matted fur and haircuts are best left to us to avoid accidental nicks.' },
      { id: 'styles', q: true,
        req: [['style*', 'styling', 'haircut*', 'puppy cut', 'teddy bear cut', 'lion cut', 'summer cut', 'breed cut', 'look like']],
        a: 'We do breed-standard cuts and popular styles like the puppy cut, teddy bear cut and summer trim, and you\'re welcome to show us a photo. Haircut/Styling starts at ₹800.' },
      { id: 'shave', q: true,
        req: [['shave*', 'shaving', 'shaved']],
        a: 'We usually don\'t recommend fully shaving double-coated breeds like Huskies or Golden Retrievers, since their coat helps them regulate temperature; a de-shed and tidy trim works better. For single-coated breeds, a short summer cut is fine.' },
      { id: 'hygiene', q: true,
        req: [['hygiene', 'hygienic', 'sanitiz*', 'sanitis*', 'safe', 'safety', 'sterile', 'injur*', 'hurt', 'cleanliness', 'accident*']],
        a: 'Safety comes first: every table, tool and tub is cleaned and sanitised between pets, and our groomers are trained in gentle, secure handling. If anything ever happens during a visit, we\'ll tell you straight away, and our vet is right on site.' },
      { id: 'photos', q: true,
        req: [['photo*', 'picture*', 'pics', 'updates', 'video*', 'cctv', 'camera']],
        a: 'Of course! We\'re happy to send you a photo or a quick update during longer sessions; just mention it at check-in. You\'ll get a proper before-and-after look at pickup too.' },
      { id: 'gift', q: true,
        req: [['gift card*', 'voucher*', 'gift certificate*', 'gift']],
        a: 'We don\'t offer gift cards just yet, but it\'s on our wish list! You can ask the team at {phone} for any current offers.' },
      { id: 'cat_water', q: true,
        req: [['cat', 'cats', 'kitten*'], ['water', 'hate*', 'hates', 'scared of water', 'bath*', 'bathe']],
        a: 'Lots of cats aren\'t fans of water, so we use warm water, quiet dryers, gentle handling and as little bathing as needed. For very anxious cats, a waterless clean or brush-out is a great alternative.' },
      { id: 'birds', q: true,
        req: [['bird*', 'parrot*', 'budgie*', 'cockatiel*', 'lovebird*', 'macaw*', 'conure*', 'finch*', 'canar*'], ['groom*', 'trim*', 'wing*', 'beak*', 'nail*', 'clip*', 'care', 'do you', 'handle', 'treat']],
        a: 'Yes, we groom birds! We offer gentle nail trims, beak checks and wing trims, handled calmly by staff experienced with birds. Bring your bird in a secure carrier; the visit is usually quick.' },
      { id: 'rabbits', q: true,
        req: [['rabbit*', 'bunny', 'bunnies'], ['groom*', 'trim*', 'nail*', 'brush*', 'care', 'do you', 'handle', 'treat']],
        a: 'Yes, we groom rabbits! They get gentle brushing, nail trims and coat care, always without full water baths, which stress rabbits out. Long-haired breeds like Angoras may need regular visits.' },
      { id: 'new_pet',
        req: [['new puppy', 'new kitten', 'just adopted', 'just got a', 'brought home', 'first checkup', 'first vet', 'adopted a']],
        a: 'Congratulations on your new family member! 🐾 Our Puppy/Kitten First Visit ({price:firstvisit}) includes a full health check, a vaccination and deworming plan, and lots of tips on feeding, training and grooming.' },
      { id: 'checkup_info', q: true,
        req: [['checkup', 'check up', 'health check', 'examination', 'consultation', 'consult']],
        a: 'Our General Checkup ({price:checkup}) is a full nose-to-tail health check with our vet, with plenty of time for your questions. It\'s a great idea once a year, or twice a year for senior pets.' },
      { id: 'insurance',
        req: [['insurance', 'insured', 'claim', 'claims']],
        a: 'We don\'t bill insurance companies directly, but we give you a detailed itemised invoice that you can submit for your claim.' },
      { id: 'shop', q: true,
        req: [['sell', 'buy', 'shop', 'store', 'food', 'treats', 'accessories', 'toys', 'leash*', 'collar*', 'brushes']],
        a: 'We keep a small range of pet-safe shampoos, brushes, treats and accessories at the front desk. For food advice, our vet will guide you during your visit.' },
      { id: 'boarding',
        req: [['boarding', 'board my', 'daycare', 'day care', 'hostel', 'overnight', 'pet sitting', 'pet sitter', 'pet hotel', 'keep my dog', 'keep my cat']],
        a: 'We don\'t offer boarding or daycare at the moment, as we focus on grooming and vet care. We\'re happy to help with everything else, though!' },
      { id: 'difference', q: true,
        req: [['difference', 'vs', 'versus', 'compare', 'better'], ['deshed*', 'de-shed*', 'haircut*', 'groom*', 'bath', 'spa']],
        a: 'A Basic Bath is a wash and dry, Full Grooming adds a haircut, nails and ears, and De-shedding focuses on removing loose undercoat. The Spa Package bundles everything, plus teeth cleaning and a paw balm.' },
      { id: 'bot_identity', q: true,
        req: [['are you a bot', 'are you human', 'are you real', 'are you a robot', 'are you ai', 'are you an ai', 'who are you', 'what are you', 'real person']],
        a: 'I\'m {short}\'s friendly virtual assistant 🐾 I can answer questions about our services and prices, and book a visit for your pet.' },
      { id: 'capabilities', q: true,
        req: [['what can you do', 'how can you help', 'what do you do', 'help me with', 'what can i ask']],
        a: 'I can tell you about our grooming and vet services and prices, answer pet-care questions about {short}, and book a visit for your pet. What would you like to do?' }
    ]
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = CONFIG;
  else root.PAWCARE_CONFIG = CONFIG;
})(typeof window !== 'undefined' ? window : this);
