/*
 * PawCare Pet Clinic & Grooming — business data for the chatbot (fictional business).
 * Everything the bot "knows" lives here: contact details, hours, services, prices
 * and the Q&A library. Edit this file to adapt the bot to another business.
 *
 * Text placeholders you can use in any answer:
 *   {name} {short} {city} {address} {phone} {emergency} {email}
 *   {price:<serviceId>}  → "from $30" style price of a service
 */
(function (root) {
  var CONFIG = {
    business: {
      name: 'PawCare Pet Clinic & Grooming',
      shortName: 'PawCare',
      city: 'Austin, TX',
      street: '42 Maple Lane',
      phone: '(512) 555-0142',
      emergencyPhone: '(512) 555-0199',
      email: 'hello@pawcareclinic.com',
      currency: '$',
      openDays: [1, 2, 3, 4, 5, 6],          // 0 = Sunday … 6 = Saturday
      openTime: '09:00',
      closeTime: '19:00',
      lastSlot: '18:00',                      // last appointment start time
      slotMinutes: 30,
      minLeadMinutes: 60,                     // same-day bookings need this much notice
      bookingWindowDays: 90,
      hoursText: 'Mon–Sat, 9 AM–7 PM',
      cancellationHours: 4,
      homePickup: { available: true, radiusMiles: 5, feeEachWay: 15 },
      multiPetDiscount: 10                    // % off every extra pet in the same visit
    },

    /* Pets we serve. "group" drives pet-specific answers and pricing size. */
    pets: [
      { id: 'dog', label: 'dog', plural: 'dogs', emoji: '🐶', group: 'dog', words: ['dog', 'dogs', 'puppy', 'puppies', 'pup', 'pups', 'doggy', 'doggo', 'pooch'] },
      { id: 'cat', label: 'cat', plural: 'cats', emoji: '🐱', group: 'cat', words: ['cat', 'cats', 'kitten', 'kittens', 'kitty', 'kitties'] },
      { id: 'bird', label: 'bird', plural: 'birds', emoji: '🐦', group: 'bird', words: ['bird', 'birds', 'parrot', 'parrots', 'budgie', 'budgies', 'cockatiel', 'cockatiels', 'lovebird', 'lovebirds', 'macaw', 'macaws', 'conure', 'conures', 'canary', 'canaries', 'finch', 'finches', 'cockatoo', 'cockatoos', 'parakeet', 'parakeets'] },
      { id: 'rabbit', label: 'rabbit', plural: 'rabbits', emoji: '🐰', group: 'rabbit', words: ['rabbit', 'rabbits', 'bunny', 'bunnies'] },
      { id: 'hamster', label: 'hamster', plural: 'hamsters', emoji: '🐹', group: 'small', words: ['hamster', 'hamsters'] },
      { id: 'guinea pig', label: 'guinea pig', plural: 'guinea pigs', emoji: '🐹', group: 'small', words: ['guinea pig', 'guinea pigs', 'guineapig', 'cavy'] },
      { id: 'sheep', label: 'sheep', plural: 'sheep', emoji: '🐑', group: 'farm', words: ['sheep', 'lamb', 'lambs', 'ewe', 'ram'] },
      { id: 'goat', label: 'goat', plural: 'goats', emoji: '🐐', group: 'farm', words: ['goat', 'goats'] },
      { id: 'cow', label: 'cow', plural: 'cows', emoji: '🐄', group: 'farm', words: ['cow', 'cows', 'calf', 'calves', 'cattle', 'buffalo', 'bull'] },
      { id: 'horse', label: 'horse', plural: 'horses', emoji: '🐴', group: 'farm', words: ['horse', 'horses', 'pony', 'ponies', 'foal', 'mare', 'stallion'] },
      { id: 'other', label: 'pet', plural: 'pets', emoji: '🐾', group: 'small', words: ['ferret', 'ferrets', 'turtle', 'turtles', 'tortoise', 'tortoises', 'chinchilla', 'chinchillas', 'hedgehog', 'hedgehogs', 'gerbil', 'gerbils', 'mouse', 'mice', 'rat', 'rats', 'iguana', 'lizard', 'snake'] }
    ],

    /* Breeds → pet type and size (s / m / l) used for price estimates. */
    breeds: {
      dog: {
        s: ['chihuahua', 'pomeranian', 'pom', 'shih tzu', 'shihtzu', 'shih-tzu', 'yorkie', 'yorkshire terrier', 'maltese', 'pug', 'dachshund', 'toy poodle', 'miniature poodle', 'lhasa apso', 'lhasa', 'papillon', 'miniature pinscher', 'min pin', 'jack russell', 'cavalier', 'king charles', 'french bulldog', 'frenchie', 'bichon', 'bichon frise', 'havanese', 'westie', 'west highland terrier', 'miniature schnauzer', 'spitz', 'pekingese', 'boston terrier', 'cockapoo', 'maltipoo', 'shih poo', 'cairn terrier', 'scottish terrier', 'italian greyhound'],
        m: ['beagle', 'cocker spaniel', 'cocker', 'border collie', 'bulldog', 'english bulldog', 'corgi', 'australian shepherd', 'aussie', 'shiba inu', 'shiba', 'basset hound', 'basset', 'indie', 'schnauzer', 'bull terrier', 'staffy', 'staffordshire terrier', 'whippet', 'springer spaniel', 'chow chow', 'chow', 'labradoodle', 'goldendoodle', 'pit bull', 'pitbull', 'american bully', 'australian cattle dog', 'heeler', 'brittany', 'sheltie', 'shetland sheepdog', 'mini aussie', 'mutt'],
        l: ['labrador', 'labrador retriever', 'lab', 'golden retriever', 'golden', 'retriever', 'german shepherd', 'gsd', 'alsatian', 'rottweiler', 'rottie', 'doberman', 'dobermann', 'boxer', 'great dane', 'saint bernard', 'st bernard', 'newfoundland', 'bernese', 'bernese mountain dog', 'mastiff', 'bullmastiff', 'husky', 'siberian husky', 'malamute', 'alaskan malamute', 'akita', 'great pyrenees', 'rhodesian ridgeback', 'weimaraner', 'belgian malinois', 'malinois', 'cane corso', 'dogo argentino', 'standard poodle', 'poodle', 'samoyed', 'dalmatian', 'irish setter', 'old english sheepdog', 'leonberger', 'tibetan mastiff', 'bernedoodle', 'german shorthaired pointer', 'vizsla']
      },
      cat: {
        s: ['persian', 'siamese', 'bengal', 'ragdoll', 'british shorthair', 'sphynx', 'himalayan', 'scottish fold', 'abyssinian', 'russian blue', 'exotic shorthair', 'domestic shorthair', 'domestic longhair', 'burmese', 'birman', 'tabby', 'calico', 'american shorthair', 'turkish angora', 'devon rex', 'tuxedo'],
        m: ['maine coon', 'norwegian forest', 'savannah']
      },
      bird: { s: ['parrot', 'budgie', 'budgerigar', 'cockatiel', 'lovebird', 'macaw', 'african grey', 'cockatoo', 'conure', 'finch', 'canary', 'pigeon', 'parakeet', 'ringneck', 'sun conure', 'eclectus'] },
      rabbit: { s: ['lionhead', 'holland lop', 'mini lop', 'netherland dwarf', 'angora', 'rex', 'dutch', 'flemish giant', 'mini rex', 'english lop', 'new zealand white'] },
      hamster: { s: ['syrian', 'dwarf', 'roborovski', 'campbell', 'winter white', 'teddy bear hamster'] },
      'guinea pig': { s: ['peruvian', 'teddy', 'american', 'skinny pig', 'texel', 'silkie'] },
      sheep: { s: ['merino', 'suffolk', 'dorper', 'katahdin', 'dorset', 'hampshire', 'romney'] },
      goat: { s: ['boer', 'nubian', 'saanen', 'nigerian dwarf', 'alpine', 'lamancha', 'pygmy', 'kiko'] },
      cow: { s: ['angus', 'hereford', 'jersey', 'holstein', 'longhorn', 'highland', 'brahman', 'charolais', 'guernsey'] },
      horse: { s: ['quarter horse', 'thoroughbred', 'arabian', 'shetland', 'mustang', 'friesian', 'appaloosa', 'paint horse', 'clydesdale', 'morgan', 'tennessee walker'] }
    },

    /*
     * Services. prices = [small, medium, large] or flat. "kw" = words that map a
     * customer's need to this service. "dur" = typical duration.
     */
    services: [
      { id: 'bath', name: 'Basic Bath', cat: 'groom', prices: [30, 40, 55], dur: 'about 45–60 minutes', kw: ['bath', 'bathe', 'bathing', 'wash', 'washing', 'shower', 'shampoo', 'smells', 'smelly', 'stinky', 'stinks', 'dirty', 'muddy'] },
      { id: 'groom', name: 'Full Grooming', cat: 'groom', prices: [55, 70, 90], dur: 'about 1.5–2.5 hours', kw: ['full groom', 'full grooming', 'grooming', 'groom', 'complete groom', 'makeover', 'grooming session'] },
      { id: 'deshed', name: 'De-shedding', cat: 'groom', prices: [45, 60, 75], dur: 'about 1–1.5 hours', kw: ['deshed', 'deshedding', 'shedding', 'sheds', 'shed', 'undercoat', 'loose hair', 'losing fur', 'moulting', 'molting', 'blowout'] },
      { id: 'haircut', name: 'Haircut/Styling', cat: 'groom', prices: [45, 60, 75], dur: 'about 1–1.5 hours', kw: ['haircut', 'hair cut', 'styling', 'style', 'trim his hair', 'trim her hair', 'trim', 'clip', 'clipping', 'shave', 'summer cut', 'puppy cut', 'teddy bear cut', 'lion cut', 'fur cut'] },
      { id: 'nail', name: 'Nail Trim', cat: 'groom', prices: [15, 15, 20], dur: 'about 15 minutes', kw: ['nail', 'nails', 'claw', 'claws', 'nail trim', 'nail cut', 'pedicure', 'paw trim'] },
      { id: 'ear', name: 'Ear Cleaning', cat: 'groom', prices: [15, 15, 20], dur: 'about 15 minutes', kw: ['ear cleaning', 'clean ears', 'clean his ears', 'clean her ears', 'ears cleaned', 'ear clean', 'ears'] },
      { id: 'teeth', name: 'Teeth Cleaning', cat: 'groom', prices: [20, 25, 30], dur: 'about 20–30 minutes', kw: ['teeth', 'tooth', 'dental', 'teeth cleaning', 'brush teeth', 'bad breath', 'tartar'] },
      { id: 'flea', name: 'Flea & Tick Treatment', cat: 'groom', prices: [35, 45, 55], dur: 'about 45 minutes', kw: ['flea', 'fleas', 'tick', 'ticks', 'lice', 'flea treatment', 'tick treatment', 'parasites'] },
      { id: 'matted', name: 'Matted Fur Removal', cat: 'groom', prices: [40, 55, 70], dur: 'about 1–2 hours', kw: ['matted', 'mats', 'matting', 'tangles', 'tangled', 'knots', 'knotted', 'clumps'] },
      { id: 'spa', name: 'Spa Package', cat: 'groom', prices: [80, 100, 125], dur: 'about 2.5–3 hours', kw: ['spa', 'spa package', 'spa day', 'pamper', 'pampering', 'luxury'] },
      { id: 'vacc', name: 'Vaccination', cat: 'vet', prices: [25, 30, 35], perUnit: 'per vaccine', dur: 'about 20 minutes', kw: ['vaccination', 'vaccinations', 'vaccine', 'vaccines', 'vaccinate', 'vaccinated', 'shots', 'shot', 'jab', 'jabs', 'booster', 'rabies'] },
      { id: 'checkup', name: 'General Checkup', cat: 'vet', prices: [55, 60, 65], dur: 'about 30 minutes', kw: ['checkup', 'check up', 'check-up', 'health check', 'general checkup', 'examination', 'consultation', 'vet visit', 'see a vet', 'see the vet', 'vet check', 'wellness exam', 'concern'] },
      { id: 'deworm', name: 'Deworming', cat: 'vet', prices: [20, 25, 30], dur: 'about 10 minutes', kw: ['deworm', 'deworming', 'dewormed', 'worms', 'worming'] },
      { id: 'microchip', name: 'Microchipping', cat: 'vet', flat: 45, dur: 'about 10 minutes', kw: ['microchip', 'microchipping', 'microchipped', 'chip', 'chipped', 'chipping'] },
      { id: 'firstvisit', name: 'Puppy/Kitten First Visit', cat: 'vet', flat: 65, dur: 'about 45 minutes', kw: ['puppy visit', 'kitten visit', 'puppy first visit', 'kitten first visit', 'new puppy', 'new kitten', 'just adopted'] },
      { id: 'spay', name: 'Spay/Neuter Consultation', cat: 'vet', flat: 50, dur: 'about 30 minutes', kw: ['spay', 'spaying', 'spayed', 'neuter', 'neutering', 'neutered', 'castrate', 'castration', 'sterilize', 'sterilise', 'sterilization', 'desex', 'fixed'] },
      { id: 'senior', name: 'Senior Pet Checkup', cat: 'vet', prices: [80, 90, 100], dur: 'about 45 minutes', kw: ['senior checkup', 'senior check', 'senior pet checkup', 'senior care', 'old age checkup'] },
      { id: 'farm', name: 'Farm Animal Visit', cat: 'farm', from: 120, onRequest: true, dur: 'depends on the herd size', kw: ['farm visit', 'farm animal visit', 'farm call', 'visit my farm', 'come to my farm', 'come to the farm'] }
    ],

    /* Quick-reply buttons for common questions (always visible, never for single services). */
    quickReplies: [
      { label: '📅 Book a visit', value: 'Book a visit' },
      { label: '🗓️ Book an appointment', value: 'Book an appointment' },
      { label: '💲 Services & prices', value: 'Services & prices?' },
      { label: '🕘 Opening hours', value: 'Opening hours?' },
      { label: '📍 Location', value: 'Location?' },
      { label: '🚗 Home pickup', value: 'Home pickup?' },
      { label: '🚨 Emergency', value: 'Emergency?' }
    ],

    ui: {
      batchDelayMs: 4000,   // wait this long after the last message/keystroke before replying
      chipDelayMs: 1500,    // shorter wait after tapping a button
      autoOpen: false
    },

    /*
     * Q&A library (short, non-medical answers). Each entry:
     *   req: groups of keywords — at least one keyword from EVERY group must appear.
     *        "word*" matches any ending (groom* → grooming, groomer…).
     *   k:   optional bonus keywords.
     *   q:   true → only answered when the message is a question.
     *   a:   the answer, or { dog, cat, bird, rabbit, small, farm, default } for pet-specific answers.
     */
    qa: [
      /* ---------- grooming basics ---------- */
      { id: 'groom_freq', q: true,
        req: [['how often', 'how frequently', 'frequency', 'how many times', 'how regularly', 'how frequent', 'how long between', 'when should'], ['groom*', 'haircut*', 'groomer']],
        a: {
          dog: 'Long or curly coats do best with a groom every 4–6 weeks, short coats every 6–12 weeks.',
          cat: 'Most cats need a professional groom every 6–12 weeks, long-haired breeds a little more often.',
          bird: 'Most birds need a nail, beak or wing trim every 1–3 months.',
          rabbit: 'Rabbits need a nail trim every 4–6 weeks and brushing a few times a week.',
          small: 'Small pets mostly need a gentle nail trim every 4–8 weeks.',
          farm: 'It depends on the season; our Farm Animal Visit team will set a routine with you.',
          default: 'Most dogs need a groom every 4–8 weeks and cats every 6–12 weeks.'
        } },
      { id: 'bath_freq', q: true,
        req: [['how often', 'how frequently', 'frequency', 'how many times', 'how regularly', 'how frequent', 'when should'], ['bath*', 'wash*', 'shampoo*']],
        a: {
          dog: 'Most dogs need a bath every 4–6 weeks; too often can dry out their skin.',
          cat: 'Most cats rarely need a bath, usually only when they get into something messy.',
          rabbit: 'Rabbits shouldn\'t get full water baths; brushing and spot-cleaning are best.',
          bird: 'Most birds enjoy a light misting or a shallow water dish a few times a week.',
          small: 'Hamsters and guinea pigs shouldn\'t be bathed in water; gentle spot-cleaning is enough.',
          farm: 'Farm animals usually only need a wash before shows or when very dirty.',
          default: 'Dogs usually need a bath every 4–6 weeks; cats and small pets rarely need one.'
        } },
      { id: 'brush_freq', q: true,
        req: [['how often', 'how frequently', 'how many times', 'should i'], ['brush*', 'comb*']],
        a: 'Long coats need brushing every day or two, short coats about once a week. It keeps mats away and spreads natural oils.' },
      { id: 'first_groom', q: true,
        req: [['puppy', 'puppies', 'kitten*', 'young', 'baby', 'babies'], ['first*', 'start*', 'what age', 'how old', 'how young', 'old enough', 'when can', 'when should']],
        k: ['groom*', 'bath*', 'haircut'],
        a: 'Puppies and kittens can start gentle grooming once they\'ve had their first vaccines, usually around 12–16 weeks. We keep the first visit short and fun.' },
      { id: 'when_needs_groom', q: true,
        req: [['how do i know', 'how can i tell', 'signs', 'when does', 'does my dog need', 'does my cat need', 'need a groom']],
        a: 'Knots, a smell, long nails clicking on the floor, or fur covering the eyes all mean it\'s time for a groom.' },
      { id: 'vacc_before_groom', q: true,
        req: [['vaccin*', 'shot', 'shots', 'jab*', 'rabies'], ['groom*', 'bath*', 'haircut*', 'spa', 'before']],
        a: 'Yes, pets need to be up to date on core vaccines like Rabies, Distemper and Bordetella before grooming. We can give any that are due at the same visit.' },
      { id: 'bordetella', boost: 0.75, req: [['bordetella', 'kennel cough']],
        a: 'We ask dogs to be up to date on Bordetella (kennel cough) before grooming. Our vet can give it at the same visit.' },
      { id: 'rabies_required', q: true, req: [['rabies'], ['required', 'law', 'need', 'mandatory', 'must', 'legal']],
        a: 'Rabies vaccination is required by law for dogs and recommended for cats. Our vet can update it during any visit.' },
      { id: 'matted',
        req: [['mat', 'mats', 'matted', 'matting', 'tangle*', 'knot*', 'clump*', 'dreadlock*']],
        a: 'Matted fur pulls on the skin, so it\'s best removed by a pro. Our Matted Fur Removal starts at $40.' },
      { id: 'shedding',
        req: [['shed', 'sheds', 'shedding', 'moult*', 'molt*', 'hair everywhere', 'fur everywhere', 'losing hair', 'losing fur', 'loose hair', 'undercoat', 'blowout']],
        a: 'Some shedding is normal, especially in spring and fall. Our De-shedding treatment (from $45) removes loose undercoat.' },
      { id: 'anxious',
        req: [['anxious', 'anxiety', 'nervous', 'scared', 'afraid', 'fearful', 'frightened', 'stressed', 'stress', 'panics', 'panic', 'timid', 'shy', 'hates grooming', 'hates baths', 'hates the groomer', 'hates the vet', 'gets scared']],
        a: 'Anxious pets are in good hands: we go slowly, use treats and take breaks. Just mention it when booking and we\'ll allow extra time.' },
      { id: 'aggressive',
        req: [['bite', 'bites', 'biting', 'bit someone', 'aggressive', 'aggression', 'snaps', 'snapping', 'growls', 'growling', 'attacks', 'reactive', 'not friendly', 'unfriendly']],
        a: 'Thanks for telling us. Our team is experienced with reactive pets, uses gentle handling and may use a soft muzzle for safety.' },
      { id: 'senior',
        req: [['senior dog*', 'senior cat*', 'senior pet*', 'senior', 'elderly', 'geriatric', 'old dog', 'old cat', 'older dog', 'older cat', 'old pet', 'older pet', 'aging', 'ageing', 'very old', 'getting old']],
        a: 'Senior pets get shorter sessions, non-slip mats and rest breaks. We suggest a Senior Pet Checkup (from $80) about twice a year.' },
      { id: 'senior_age', q: true, req: [['what age', 'when is', 'how old'], ['senior', 'old']],
        a: 'Most dogs and cats are considered seniors from about 7–8 years, giant breeds a little earlier.' },
      { id: 'long_short_hair',
        req: [['long hair*', 'long-hair*', 'longhair*', 'short hair*', 'short-hair*', 'shorthair*', 'double coat*', 'double-coat*', 'coat type', 'fluffy', 'curly coat']],
        a: 'Long and curly coats need brushing most days and a groom every 4–6 weeks. Short coats need less trimming but still benefit from baths and de-shedding.' },
      { id: 'shave', q: true, req: [['shave*', 'shaving', 'shaved']],
        a: 'We don\'t recommend shaving double-coated breeds like Huskies or Goldens, since the coat may not grow back evenly. A de-shed and tidy trim works better.' },
      { id: 'summer_coat', q: true, req: [['summer', 'heat', 'hot weather'], ['coat', 'cut', 'groom*', 'trim*', 'fur']],
        a: 'A tidy summer trim helps many dogs stay comfy, but double coats shouldn\'t be shaved. Shade and fresh water matter most.' },
      { id: 'winter_groom', q: true, req: [['winter', 'cold weather', 'snow']],
        a: 'Keep brushing in winter to prevent mats. We always dry every pet fully before they go home.' },
      { id: 'styles', q: true,
        req: [['style*', 'styling', 'haircut*', 'puppy cut', 'teddy bear cut', 'lion cut', 'summer cut', 'breed cut', 'look like']],
        a: 'We do breed cuts and popular styles like the puppy cut and teddy bear cut; bring a photo if you like. Haircut/Styling starts at $45.' },
      { id: 'paw_pads', q: true, req: [['paw pad*', 'pads', 'paw hair', 'between toes', 'between the toes', 'feet trim']],
        a: 'We trim the fur between paw pads to prevent slipping and matting; it\'s included in Full Grooming.' },
      { id: 'sanitary', req: [['sanitary', 'potty area', 'hygiene trim']],
        a: 'A sanitary trim keeps the potty area clean and tidy, and it\'s included in Full Grooming.' },
      { id: 'tear_stains', req: [['tear stain*', 'eye stain*', 'eye gunk', 'eye boogers', 'around the eyes', 'face trim', 'face clean*']],
        a: 'We gently clean around the eyes and trim facial hair during grooming. If the eyes look red or sore, our vet can take a look.' },
      { id: 'smell', req: [['smell*', 'stink*', 'odor', 'odour']],
        a: 'A Basic Bath (from $30) usually freshens things up. If the smell comes back fast, our vet can check the skin and ears.' },
      { id: 'dry_skin', req: [['dandruff', 'dry skin', 'flaky', 'flakes']],
        a: 'We can use a gentle moisturizing shampoo. If it continues, our vet can take a look during a checkup.' },
      { id: 'human_shampoo', req: [['human shampoo', 'my shampoo', 'baby shampoo', 'dish soap', 'dawn']],
        a: 'Human shampoo can upset a pet\'s skin, so we only use pet-safe products. We\'re happy to suggest one for home.' },
      { id: 'products', q: true,
        req: [['shampoo*', 'product*', 'conditioner*', 'chemical*', 'organic', 'natural', 'hypoallergenic']],
        a: 'We use gentle, soap-free, pet-safe shampoos, including hypoallergenic options. You\'re welcome to bring your own too.' },
      { id: 'bows', req: [['bow', 'bows', 'bandana*', 'cologne', 'perfume', 'spritz']],
        a: 'Every groom can finish with a light pet-safe spritz and a bandana or bow. Just ask!' },
      { id: 'home_bath', q: true,
        req: [['at home', 'myself', 'my own', 'diy', 'home groom*', 'by myself'], ['bath*', 'groom*', 'trim*', 'cut*', 'brush*', 'wash*']],
        a: 'Yes: use a pet-safe shampoo and lukewarm water, rinse well and dry fully. Leave nail trims and haircuts to us to avoid nicks.' },
      { id: 'difference', q: true,
        req: [['difference', 'vs', 'versus', 'compare', 'better'], ['deshed*', 'de-shed*', 'haircut*', 'groom*', 'bath', 'spa']],
        a: 'A Basic Bath is a wash and dry; Full Grooming adds a haircut, nails and ears. The Spa Package adds teeth cleaning and a paw balm.' },
      { id: 'packages',
        req: [['package*', 'combo*', 'bundle*', 'deal', 'deals', 'special offer*', 'discount*', 'promo*', 'coupon*', 'membership']],
        a: 'Our Spa Package (from $80) bundles bath, groom, nails, ears and teeth. Extra pets in the same visit get 10% off.' },

      /* ---------- nails, ears, teeth, eyes ---------- */
      { id: 'nails', q: true, req: [['nail*', 'claw*']],
        a: 'Most pets need a nail trim every 3–6 weeks; clicking on the floor means it\'s time. Our Nail Trim is $15.' },
      { id: 'nail_fear', req: [['nail*', 'claw*'], ['scared', 'hate*', 'afraid', 'fear*', 'nervous', 'fight*', 'wont let']],
        a: 'Lots of pets dislike nail trims, so we go slowly with treats and breaks. Short, regular trims make it easier over time.' },
      { id: 'nail_quick', req: [['quick', 'bleed*', 'too short'], ['nail*', 'claw*']],
        a: 'If a nail is cut too short it may bleed a little, and we keep styptic powder ready. Bleeding that won\'t stop needs a vet right away.' },
      { id: 'nail_grind', req: [['grind*', 'dremel', 'file the nails', 'filing']],
        a: 'Yes, we smooth nails with a gentle grinder after trimming at no extra cost.' },
      { id: 'cat_nails', q: true, req: [['cat', 'cats', 'kitten*'], ['nail*', 'claw*']],
        a: 'Most cats need a nail trim every 2–4 weeks, and it only takes a few minutes. Our Nail Trim is $15.' },
      { id: 'declaw', req: [['declaw*']],
        a: 'We don\'t offer declawing. Regular nail trims and scratching posts are kinder options.' },
      { id: 'ears', q: true, req: [['ear', 'ears']],
        a: 'Check ears weekly and clean every 2–4 weeks, more often for floppy-eared breeds. Our Ear Cleaning is $15.' },
      { id: 'ear_hair', req: [['ear', 'ears'], ['hair', 'pluck*']],
        a: 'We trim or gently remove extra ear hair only when needed, usually for breeds like Poodles.' },
      { id: 'anal_glands', req: [['anal', 'gland', 'glands', 'scooting', 'scoots']],
        a: 'Our team can express glands on request during a visit. If your pet scoots a lot, a checkup is a good idea.' },
      { id: 'dental', q: true, req: [['teeth', 'tooth', 'dental', 'breath', 'tartar', 'gums']],
        a: 'Brushing a few times a week with pet toothpaste is the best habit. Our Teeth Cleaning starts at $20.' },

      /* ---------- parasites ---------- */
      { id: 'flea_tick', q: true, req: [['flea*', 'tick', 'ticks', 'lice', 'parasite*']],
        a: 'Check ears, neck and between the toes for fleas and ticks. Our Flea & Tick Treatment starts at $35, and our vet can advise on prevention.' },
      { id: 'flea_home', req: [['flea*'], ['house', 'home', 'carpet*', 'bed', 'bedding', 'furniture', 'couch', 'sofa']],
        a: 'Wash bedding in hot water and vacuum often. Our vet can advise on prevention for your pet.' },
      { id: 'tick_remove', req: [['tick', 'ticks'], ['remove', 'removal', 'pull', 'found', 'get rid', 'stuck']],
        a: 'Grip the tick close to the skin with fine tweezers and pull straight out, or we can remove it for you.' },
      { id: 'heartworm', req: [['heartworm*']],
        a: 'Our vet will guide you on heartworm prevention during your visit.' },
      { id: 'deworm', q: true, req: [['deworm*', 'worm', 'worms', 'worming']],
        a: 'Our vet will set the right deworming routine for your pet. Deworming starts at $20.' },

      /* ---------- vet care ---------- */
      { id: 'vacc_schedule', q: true,
        req: [['vaccin*', 'shot', 'shots', 'jab*', 'booster*'], ['when', 'schedule', 'how often', 'which', 'what', 'age', 'due', 'how many']],
        a: 'Puppies and kittens usually start vaccines at 6–8 weeks, but our vet will set the exact schedule. Vaccines start at $25 each.' },
      { id: 'vacc_side', req: [['side effect*', 'reaction*', 'after vaccin*', 'after the shot', 'after shots']],
        a: 'Our vet will guide you on that during your visit. You can call us at {phone} any time.' },
      { id: 'vacc_records',boost: 0.75, 
        req: [['record*', 'certificate*', 'card', 'proof', 'booklet', 'papers'], ['vaccin*', 'health', 'medical', 'shot', 'shots']],
        a: 'Yes, please bring vaccination records; a photo on your phone works too.' },
      { id: 'records_transfer', req: [['transfer', 'send', 'share', 'forward'], ['record*', 'history', 'files']],
        a: 'Just ask your previous vet to email the records to {email}, or bring them along.' },
      { id: 'checkup_info', q: true,
        req: [['checkup', 'check up', 'health check', 'examination', 'consultation', 'consult', 'wellness']],
        a: 'Our General Checkup (from $55) is a full nose-to-tail exam. Once a year is ideal, twice for seniors.' },
      { id: 'microchip', req: [['microchip*', 'chip', 'chipping', 'chipped']],
        a: 'Microchipping is a quick, one-time $45 procedure that helps lost pets get home.' },
      { id: 'lost_found', req: [['lost', 'found a', 'stray'], ['pet', 'dog', 'cat', 'puppy', 'kitten']],
        a: 'Bring a found pet in during opening hours and we\'ll scan for a microchip for free.' },
      { id: 'spay_neuter', req: [['spay*', 'neuter*', 'castrat*', 'steriliz*', 'sterilis*', 'desex*']],
        a: 'Our vet will talk through the right timing at a Spay/Neuter Consultation ($50).' },
      { id: 'new_pet',
        req: [['new puppy', 'new kitten', 'just adopted', 'just got a', 'brought home', 'first checkup', 'first vet', 'adopted a']],
        a: 'Congratulations! 🐾 Our Puppy/Kitten First Visit ($65) covers a health check plus a vaccine and deworming plan.' },
      { id: 'weight', req: [['overweight', 'weight', 'fat', 'chubby', 'obese', 'too thin', 'skinny']],
        a: 'Our vet can check your pet\'s weight and give tailored advice during a checkup.' },
      { id: 'travel', req: [['travel', 'health certificate', 'fly', 'flight', 'airline', 'moving abroad']],
        a: 'Our vet can do a pre-travel checkup. Please call {phone} about paperwork for your destination.' },
      { id: 'second_opinion', req: [['second opinion']],
        a: 'Of course, our vets are happy to give a second opinion. Please bring any previous records.' },
      { id: 'end_of_life', req: [['euthanas*', 'put down', 'put to sleep', 'end of life', 'saying goodbye']],
        a: 'We\'re so sorry you\'re facing this. Please call us at {phone} and our vet team will talk it through gently.' },
      { id: 'sedation', boost: 0.75, req: [['sedat*', 'anaesthe*', 'anesthe*', 'tranquil*', 'drugged']],
        a: 'We never sedate for routine grooming. Any sedation for medical care is decided only by our vet after an exam.' },
      { id: 'food', q: true, req: [['food', 'diet', 'feed', 'kibble', 'treats'], ['what', 'which', 'best', 'recommend', 'should']],
        a: 'Our vet will guide you on the best food for your pet during your visit.' },
      { id: 'feed_before', req: [['feed', 'eat', 'food', 'fast', 'fasting', 'breakfast'], ['before']],
        a: 'A light meal a few hours before grooming is fine. For vet procedures, we\'ll tell you if fasting is needed.' },

      /* ---------- other animals ---------- */
      { id: 'pets_served', q: true, fallback: true,
        req: [['groom*', 'treat', 'accept', 'take', 'handle', 'serve', 'see', 'cater', 'work with', 'allowed', 'care for', 'look after', 'do you do'], ['cat', 'cats', 'dog', 'dogs', 'pets', 'animals', 'exotic*', 'puppies', 'kittens', 'small animals', 'which animals', 'what animals', 'kind of pets', 'types of pets']],
        a: 'We care for dogs, cats, birds, rabbits, hamsters, guinea pigs and farm animals like sheep, goats, cows and horses.' },
      { id: 'cat_water', q: true, req: [['cat', 'cats', 'kitten*'], ['water', 'hate*', 'hates', 'scared of water', 'bath*', 'bathe']],
        a: 'Many cats dislike water, so we use warm water, quiet dryers and as little bathing as possible. A waterless clean is another option.' },
      { id: 'birds', q: true,
        req: [['bird*', 'parrot*', 'budgie*', 'cockatiel*', 'lovebird*', 'macaw*', 'conure*', 'finch*', 'canar*', 'parakeet*'], ['groom*', 'trim*', 'wing*', 'beak*', 'nail*', 'clip*', 'care', 'do you', 'handle', 'treat']],
        a: 'Yes, we do gentle nail, beak and wing trims for birds. Please bring your bird in a secure carrier.' },
      { id: 'rabbits', q: true,
        req: [['rabbit*', 'bunny', 'bunnies'], ['groom*', 'trim*', 'nail*', 'brush*', 'care', 'do you', 'handle', 'treat']],
        a: 'Yes, we groom rabbits with gentle brushing and nail trims, never full water baths.' },
      { id: 'small_teeth', req: [['rabbit*', 'bunny', 'guinea pig*', 'hamster*'], ['teeth', 'tooth']],
        a: 'Rabbit and rodent teeth grow all the time, so our vet checks them at every visit.' },
      { id: 'small_pets', q: true, req: [['hamster*', 'guinea pig*', 'gerbil*', 'chinchilla*'], ['groom*', 'care', 'nail*', 'bath*', 'do you', 'treat']],
        a: 'We do gentle nail trims and coat checks for small pets. They should never be bathed in water.' },
      { id: 'other_pets',
        req: [['ferret*', 'turtle*', 'tortoise*', 'chinchilla*', 'hedgehog*', 'gerbil*', 'mouse', 'mice', 'rats', 'fish', 'snake*', 'lizard*', 'iguana*', 'exotic*', 'reptile*']],
        a: 'We see many small and exotic pets for nail trims and checkups. Tell us what you have and we\'ll confirm.' },
      { id: 'farm',
        req: [['farm', 'farms', 'sheep', 'goat*', 'cow', 'cows', 'cattle', 'horse*', 'pony', 'ponies', 'livestock', 'donkey*', 'alpaca*', 'llama*']],
        a: 'Yes! Our Farm Animal Visit for sheep, goats, cows and horses starts at $120 plus travel.' },
      { id: 'farm_vet', req: [['goat*', 'cow*', 'cattle', 'sheep', 'horse*', 'livestock'], ['vaccin*', 'deworm*', 'checkup', 'check up', 'vet']],
        a: 'Yes, our team handles farm vaccinations, deworming and checkups on site, from $120 plus travel.' },
      { id: 'hooves', boost: 0.75, req: [['hoof', 'hooves', 'farrier']],
        a: 'Our Farm Animal Visit includes hoof checks, and we can recommend a farrier for full trims.' },
      { id: 'shearing', boost: 0.75, req: [['shear*', 'wool', 'fleece']],
        a: 'We can arrange shearing during a Farm Animal Visit, usually once a year in spring.' },

      /* ---------- visit logistics ---------- */
      { id: 'what_to_bring', q: true,
        req: [['what should i bring', 'what to bring', 'what do i bring', 'what do i need to bring', 'should i bring anything', 'bring anything', 'anything to bring', 'what should i carry', 'how to prepare', 'how should i prepare', 'what do i need for']],
        a: 'Bring your pet on a leash or in a carrier, plus any vaccination records. A favorite toy helps too!' },
      { id: 'carrier', req: [['carrier', 'crate', 'leash']],
        a: 'Please bring cats and small pets in a secure carrier; dogs should be on a leash.' },
      { id: 'duration', q: true,
        req: [['how long', 'how much time', 'duration', 'take long', 'takes long', 'how many hours', 'how many minutes']],
        a: 'A bath takes about an hour and Full Grooming 1.5–2.5 hours. A nail trim takes about 15 minutes.' },
      { id: 'collect_time', req: [['when can i', 'what time can i', 'when do i'], ['collect', 'pick up my', 'pick him up', 'pick her up', 'get him back', 'get her back']],
        a: 'We\'ll message you as soon as your pet is ready, usually within 1–3 hours.' },
      { id: 'stay_with_pet', q: true,
        req: [['stay', 'watch', 'be with', 'accompany', 'be there', 'be present', 'in the room', 'come inside', 'wait with']], k: ['pet', 'dog', 'cat', 'during', 'while', 'groom*'],
        a: 'You\'re welcome to stay for vet visits. For grooming, pets often settle better alone, but you can wait in our lounge.' },
      { id: 'photos', q: true, req: [['photo*', 'picture*', 'pics', 'updates', 'video*', 'camera', 'webcam']],
        a: 'Of course! We\'re happy to send a photo update during longer sessions.' },
      { id: 'home_pickup',
        req: [['pickup', 'pick up', 'pick-up', 'pick him up', 'pick her up', 'pick them up', 'transport', 'come to my home', 'come to my house', 'doorstep', 'home service', 'pet taxi', 'collect my pet', 'collect my dog']],
        a: 'Yes, we offer home pickup and drop-off within 5 miles for $15 each way.' },
      { id: 'walk_in',
        req: [['walk in', 'walk-in', 'walk ins', 'walk-ins', 'walkin', 'walkins', 'without appointment', 'without an appointment', 'without booking', 'just come', 'just drop by', 'drop in', 'drop by', 'just show up', 'turn up']],
        a: 'Walk-ins are welcome when we have a free slot, but booking ahead guarantees your time.' },
      { id: 'advance', q: true, req: [['in advance', 'ahead', 'how early', 'how far'], ['book*', 'appointment*', 'schedule']],
        a: 'We suggest booking 3–7 days ahead, especially for Saturdays. You can book up to 3 months out.' },
      { id: 'reminder', req: [['reminder', 'remind']],
        a: 'We send a reminder the day before your appointment.' },
      { id: 'paperwork', q: true,
        req: [['paperwork', 'documents', 'document', 'forms', 'form', 'register', 'registration', 'new client', 'new patient']],
        a: 'There\'s just a short 5-minute registration form on your first visit. Bring any vet records you have.' },

      /* ---------- policies & payments ---------- */
      { id: 'cancellation', q: true, req: [['cancel*']],
        a: 'You can cancel or reschedule free of charge up to 4 hours before your appointment.' },
      { id: 'reschedule', q: true,
        req: [['reschedul*', 'postpone', 'move my appointment', 'move my booking', 'change my appointment', 'change my booking', 'another day', 'different day']],
        a: 'Rescheduling is free up to 4 hours before your visit. Just call us at {phone}.' },
      { id: 'late', req: [['late', 'delay*', 'running behind', 'stuck in traffic', 'few minutes late']],
        a: 'No worries, we hold your slot for 15 minutes. If you\'ll be later, please call {phone}.' },
      { id: 'no_show', req: [['no show', 'no-show', 'miss my appointment', 'missed my appointment', 'forgot my appointment']],
        a: 'Missed visits may have a $15 fee, but we\'re always happy to rebook you.' },
      { id: 'payment',
        req: [['pay', 'paying', 'payment*', 'card', 'cards', 'cash', 'credit card', 'debit card', 'apple pay', 'google pay', 'venmo', 'zelle', 'paypal', 'contactless']],
        a: 'We accept cash, all major cards, Apple Pay and Google Pay. Payment is made after the service.' },
      { id: 'deposit', boost: 0.75, req: [['deposit', 'prepay*', 'pay upfront', 'pay in advance', 'advance payment']],
        a: 'No deposit is needed; you pay at the clinic after the service.' },
      { id: 'payment_plan', req: [['payment plan', 'installment*', 'financing', 'afford', 'too expensive', 'cheaper option']],
        a: 'We don\'t offer payment plans yet, but we\'re happy to suggest options that fit your budget.' },
      { id: 'tipping', req: [['tip', 'tips', 'tipping', 'gratuity']],
        a: 'Tips are never expected, but our team always appreciates them!' },
      { id: 'refund', req: [['refund', 'not happy', 'unhappy', 'complain*', 'redo', 'bad haircut', 'unsatisfied']],
        a: 'If you\'re not happy with a groom, tell us within 3 days and we\'ll fix it for free.' },
      { id: 'insurance', req: [['insurance', 'insured', 'claim', 'claims']],
        a: 'We don\'t bill insurers directly, but we give you an itemized invoice for your claim.' },
      { id: 'how_much_multi', q: true,
        req: [['how much', 'price', 'prices', 'cost', 'costs', 'charge', 'charges', 'rate', 'rates'], ['2', 'two', '3', 'three', '4', 'four', 'multiple', 'both', 'couple', 'several'], ['dogs', 'cats', 'pets', 'puppies', 'kittens', 'animals', 'rabbits', 'birds']],
        a: 'Each pet is priced by size, and the second pet in the same visit gets 10% off. For example, two Basic Baths start at $57.' },
      { id: 'multi_discount',
        req: [['discount*', 'cheaper', 'deal', 'offer', 'less', 'concession'], ['multiple', 'more than one', 'two', '2', 'three', '3', 'several', 'second', 'both', 'extra pet', 'another pet', 'all my']],
        a: 'Yes! Every extra pet in the same visit gets 10% off.' },
      { id: 'gift', q: true, req: [['gift card*', 'voucher*', 'gift certificate*', 'gift']],
        a: 'We don\'t offer gift cards yet, but it\'s on our wish list!' },

      /* ---------- the clinic ---------- */
      { id: 'hours', q: true,
        req: [['open', 'opening', 'close', 'closing', 'closed', 'timing', 'timings', 'hours', 'what time do you', 'when are you', 'working hours', 'business hours', 'office hours']],
        a: 'We\'re open Mon–Sat, 9 AM–7 PM, and closed on Sundays.' },
      { id: 'sunday', q: true, req: [['sunday', 'sundays', 'weekend', 'weekends']], k: ['open', 'closed', 'work'],
        a: 'We\'re closed on Sundays but open Saturdays, 9 AM–7 PM.' },
      { id: 'holidays', boost: 0.75, req: [['holiday*', 'christmas', 'thanksgiving', 'new year', 'easter', 'july 4', 'labor day', 'memorial day']],
        a: 'We\'re closed on major holidays. Please call {phone} for holiday hours.' },
      { id: 'location', q: true,
        req: [['where', 'address', 'location', 'located', 'directions', 'find you', 'map', 'how to reach', 'how do i get there', 'how do i get to you', 'which area', 'landmark']],
        a: 'We\'re at {address}. 🐾' },
      { id: 'parking', req: [['park', 'parking', 'car park']],
        a: 'Yes, there\'s free parking right in front of the clinic.' },
      { id: 'contact', q: true,
        req: [['phone number', 'your number', 'contact', 'call you', 'email', 'reach you', 'telephone', 'get in touch', 'talk to someone', 'speak to someone', 'human', 'real person']],
        a: 'You can call us at {phone} or email {email}.' },
      { id: 'emergency_info',
        req: [['emergency', 'emergencies', 'urgent', '24/7', '24 hours', '24 7', 'after hours', 'night time', 'midnight']],
        a: 'If it\'s an emergency, please take your pet to the nearest emergency vet right away. Our emergency line is {emergency}.' },
      { id: 'staff_quals', q: true,
        req: [['qualified', 'qualification*', 'certified', 'experienced', 'experience', 'expert*', 'professional*', 'skilled', 'licensed']], k: ['groomer*', 'vet', 'vets', 'staff', 'team', 'doctor*'],
        a: 'Our team includes licensed vets and certified groomers trained in gentle, low-stress handling.' },
      { id: 'hygiene', q: true,
        req: [['hygiene', 'hygienic', 'sanitiz*', 'sanitis*', 'safe', 'safety', 'sterile', 'injur*', 'hurt', 'cleanliness', 'accident*']],
        a: 'Every table, tool and tub is sanitized between pets, and our vet is always on site.' },
      { id: 'shop', q: true,
        req: [['sell', 'buy', 'shop', 'store', 'accessories', 'toys', 'leash*', 'collar*', 'brushes']],
        a: 'We sell a small range of shampoos, brushes, treats and accessories at the front desk.' },
      { id: 'boarding',boost: 0.75, 
        req: [['boarding', 'board my', 'daycare', 'day care', 'overnight', 'pet sitting', 'pet sitter', 'pet hotel', 'kennel']],
        a: 'We don\'t offer boarding or daycare; we focus on grooming and vet care.' },
      { id: 'training', q: true, req: [['train*', 'obedience', 'behavio*'], ['class*', 'teach', 'lessons', 'help with', 'do you']],
        a: 'We don\'t run training classes, but our team can share gentle handling tips during a visit.' },
      { id: 'jobs', req: [['job', 'jobs', 'hiring', 'career*', 'vacancy', 'vacancies', 'work for you', 'internship']],
        a: 'Thanks for your interest! Please email {email} with your details.' },
      { id: 'bot_identity', q: true,
        req: [['are you a bot', 'are you human', 'are you real', 'are you a robot', 'are you ai', 'are you an ai', 'who are you', 'what are you']],
        a: 'I\'m {short}\'s virtual assistant 🐾 I can answer questions and book visits for your pet.' }
    ]
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = CONFIG;
  else root.PAWCARE_CONFIG = CONFIG;
})(typeof window !== 'undefined' ? window : this);
